# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20160625_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
