# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20160626_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
